create extension if not exists "pgcrypto";

create table if not exists public.contact_requests (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null,
  whatsapp text not null,
  message text not null,
  service_slug text,
  status text not null default 'nouveau'
    check (status in ('nouveau', 'en_cours', 'repondu', 'archive')),
  created_at timestamptz not null default now()
);

create table if not exists public.website_visits (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  page_path text not null default '/',
  referrer text,
  visited_at timestamptz not null default now()
);

create index if not exists website_visits_visitor_idx on public.website_visits (visitor_id);
create index if not exists website_visits_date_idx on public.website_visits (visited_at desc);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  category text not null,
  summary text not null,
  result text,
  image_url text,
  project_url text,
  status text not null default 'draft' check (status in ('draft', 'published')),
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.services (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  short_description text not null,
  description text not null,
  benefits jsonb not null default '[]'::jsonb,
  inclusions jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.contact_requests enable row level security;
alter table public.website_visits enable row level security;
alter table public.projects enable row level security;
alter table public.services enable row level security;

create policy "Le public peut envoyer une demande"
  on public.contact_requests for insert to anon, authenticated with check (true);
create policy "Le public peut enregistrer une visite"
  on public.website_visits for insert to anon, authenticated with check (true);
create policy "Les projets publiés sont visibles"
  on public.projects for select to anon, authenticated
  using (status = 'published' or (select auth.role()) = 'authenticated');
create policy "Les services actifs sont visibles"
  on public.services for select to anon, authenticated
  using (is_active = true or (select auth.role()) = 'authenticated');

create policy "L’administrateur gère les demandes"
  on public.contact_requests for all to authenticated using (true) with check (true);
create policy "L’administrateur consulte les visites"
  on public.website_visits for select to authenticated using (true);
create policy "L’administrateur gère les projets"
  on public.projects for all to authenticated using (true) with check (true);
create policy "L’administrateur gère les services"
  on public.services for all to authenticated using (true) with check (true);

create or replace function public.get_public_visit_stats()
returns table (unique_visitors bigint, total_visits bigint)
language sql
security definer
set search_path = public
as $$
  select count(distinct visitor_id), count(*) from public.website_visits;
$$;

revoke all on function public.get_public_visit_stats() from public;
grant execute on function public.get_public_visit_stats() to anon, authenticated;
